# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            mbyim
tagline:          ''
description:      ''
url: http://mbyim.com


author:
  name:           'Martin Yim'
  url:            

paginate:         5

# Custom vars
version:          2.0.0

#github:
#  repo:           https://github.com/poole/lanyon

# Gems
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

# Google Analytics
google_analytics: UA-146812223-1
